# ****************************************************
# ********** I18N CONFIGURATION BELOW ****************
# ****************************************************
# *  This is a generic pogo configuration file.      *
# *  At minimum, specify the project name, filename, *
# *  the locale targets for translation.             *
# ****************************************************

[general]
######################################################

# Locale targets for translation - e.g. ["en_GB", "ja"]
targets             = []

# Choose a name and base filename for this pogo project.
# Generated .pot/.po files will be named accordingly.
project_name        = "My Project"
project_filename    = "my_project"

# Path of your locale directory -- note:
# - use "/" for path separator
# - %PROJECT% stands for the directory where this very file is located
#   and can be removed to specify absolute path
dir_locale          = "%PROJECT%/locale"

# Subdirectory name for specific catalogs (.po files)
dir_messages        = "LC_MESSAGES"


[parsing]
######################################################

# Where should pogo look for string literals?

# Filename extensions of the project's templates
extensions_template = ["tmpl", "html"]

# Function/method names used in your source
function_gettext    = "G"
function_ngettext   = "NG"
function_pgettext   = "PG"
function_npgettext  = "NPG"

# Template delimiters
delimiter_left      = "{{"
delimiter_right     = "}}"


[po]
######################################################

# What other information should be included in the catalogs?

# Comment boilerplate to appear at the top of po templates
comment             = "Generated by pogo\n\nTRANSLATOR COMMENTS\n"

# Who is responsible for sorting out translation-related bugs?
report_bugs_to      = "Nobody"


[meta]
######################################################

# This release metadata does not need to be altered.

pogo_version        = "0.1.0"